[package]
name = "client"
version = "0.1.0"
authors = ["anonymousGiga <cryptonymGong@gmail.com>"]
edition = "2018"



[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0"
