[package]
name = "actix_web0"
version = "0.1.0"
authors = ["Administrator"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.3"
actix-session = "0.4"
actix-utils = "2"
env_logger = "0.7"